Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -4,10 +4,9 @@ on:
   workflow_dispatch:
     inputs:
       tag:
-        description: "Select the version to deploy"
+        description: "Type the version to deploy"
         required: true
-        type: choice
-        options: ${{ github.event.repository.tags }}
+        type: string
 
 permissions: 
   checks: write
@@ -26,3 +25,10 @@ jobs:
     steps:
       - name: checkout
         uses: actions/checkout@v4
+
+      - name: Validate Tag
+        run: |
+          if ! git fetch --tags && git tag --list | grep -q "^${{ github.event.inputs.tag }}$"; then
+            echo "Error: The tag '${{ github.event.inputs.tag }}' does not exist in the repository."
+            exit 1
+          fi
